# Generated by Django 4.2.9 on 2024-01-03 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='return_policy',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warranty',
        ),
    ]
